import Link from "next/link";
import { ArrowUpRight, Bot, Clock3, ListTodo, TriangleAlert } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { updateTaskAction } from "@/lib/actions/records";
import { formatDateLabel, taskTone, type WorkflowTaskRow } from "@/lib/workflow";

function isOverdue(task: WorkflowTaskRow) {
  if (!task.due_at) return false;
  return new Date(task.due_at).getTime() < Date.now() && !["Done", "Closed"].includes(task.status);
}

export default async function TasksPage() {
  const supabase = await createClient();
  const { data: tasks, error } = await supabase.from("tasks").select("*").order("created_at", { ascending: false });

  if (error) {
    return (
      <div className="space-y-6">
        <section className="overflow-hidden rounded-[2rem] border border-white/70 bg-white/70 p-6 shadow-sm backdrop-blur md:p-8">
          <Badge tone="blue">Queue workspace</Badge>
          <h1 className="mt-4 font-display text-4xl font-semibold tracking-tight md:text-5xl">Operational task queue</h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">
            Run the workflow migration before using the task queue. The current environment has not loaded the workflow tables yet.
          </p>
        </section>
        <Card>
          <p className="text-sm text-muted-foreground">{error.message}</p>
        </Card>
      </div>
    );
  }

  const rows = (tasks ?? []) as WorkflowTaskRow[];
  const openCount = rows.filter((task) => task.status === "Open").length;
  const inProgressCount = rows.filter((task) => task.status === "In Progress").length;
  const overdueCount = rows.filter(isOverdue).length;

  return (
    <div className="space-y-6">
      <section className="overflow-hidden rounded-[2rem] border border-white/70 bg-slate-950 text-white shadow-glow">
        <div className="grid gap-6 p-6 md:grid-cols-[1.1fr_0.9fr] md:p-8">
          <div>
            <Badge className="mb-5 bg-white/10 text-white">Queue workspace</Badge>
            <h1 className="font-display text-4xl font-semibold tracking-tight md:text-6xl">Operational task queue</h1>
            <p className="mt-5 max-w-2xl text-sm leading-7 text-white/68">
              Follow-up tasks generated by operations work, workflow rules, and manual coordination all live here.
            </p>
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-3xl bg-white p-4 text-slate-950">
              <p className="text-3xl font-semibold">{openCount}</p>
              <p className="text-xs text-slate-500">Open</p>
            </div>
            <div className="rounded-3xl bg-white p-4 text-slate-950">
              <p className="text-3xl font-semibold">{inProgressCount}</p>
              <p className="text-xs text-slate-500">In progress</p>
            </div>
            <div className="rounded-3xl bg-rose-300 p-4 text-slate-950">
              <p className="text-3xl font-semibold">{overdueCount}</p>
              <p className="text-xs font-medium">Overdue</p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">My tasks</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">{rows.filter((task) => task.assigned_label).length}</p>
              <p className="mt-2 text-xs text-muted-foreground">Tasks already assigned to an owner or team.</p>
            </div>
            <Bot className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Needs review</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">
                {rows.filter((task) => task.title.toLowerCase().includes("review")).length}
              </p>
              <p className="mt-2 text-xs text-muted-foreground">Review-related follow-ups generated across the system.</p>
            </div>
            <ListTodo className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">At risk</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">
                {rows.filter((task) => task.priority === "High").length}
              </p>
              <p className="mt-2 text-xs text-muted-foreground">High-priority operational tasks requiring attention.</p>
            </div>
            <TriangleAlert className="size-5 text-muted-foreground" />
          </div>
        </Card>
      </section>

      <Card className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div>
            <h2 className="font-display text-2xl font-semibold">All tasks</h2>
            <p className="text-sm text-muted-foreground">Update ownership, due dates, or status directly from the queue.</p>
          </div>
        </div>

        <div className="space-y-3">
          {rows.length ? (
            rows.map((task) => (
              <div key={task.id} className="rounded-[1.6rem] border border-slate-200 bg-white p-4">
                <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={taskTone(task.status, task.priority)}>{task.status}</Badge>
                      <Badge>{task.priority}</Badge>
                      {isOverdue(task) ? <Badge tone="red">Overdue</Badge> : null}
                    </div>
                    <h3 className="mt-3 text-lg font-semibold text-slate-950">{task.title}</h3>
                    {task.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{task.description}</p> : null}
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Clock3 className="size-3.5" />
                        {formatDateLabel(task.due_at)}
                      </span>
                      <span>{task.assigned_label || "Unassigned"}</span>
                    </div>
                  </div>

                  <div className="w-full max-w-xl space-y-3">
                    <form action={updateTaskAction} className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]">
                      <input type="hidden" name="taskId" value={task.id} />
                      <input type="hidden" name="returnTo" value="/tasks" />
                      <select
                        name="status"
                        defaultValue={task.status}
                        className="flex h-11 w-full rounded-[1.1rem] border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-slate-400"
                      >
                        <option value="Open">Open</option>
                        <option value="In Progress">In progress</option>
                        <option value="Blocked">Blocked</option>
                        <option value="Done">Done</option>
                        <option value="Closed">Closed</option>
                      </select>
                      <input
                        name="assignedLabel"
                        defaultValue={task.assigned_label ?? ""}
                        placeholder="Owner"
                        className="h-11 rounded-[1.1rem] border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-slate-400"
                      />
                      <input
                        name="dueAt"
                        type="date"
                        defaultValue={task.due_at ? String(task.due_at).slice(0, 10) : ""}
                        className="h-11 rounded-[1.1rem] border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-slate-400"
                      />
                      <Button size="sm" variant="outline">
                        Save
                      </Button>
                    </form>
                    <Link
                      href={`/records/${task.source_record_type}/${task.source_record_id}`}
                      className="inline-flex items-center gap-2 text-sm font-medium text-slate-700 transition hover:text-slate-950"
                    >
                      Open source record
                      <ArrowUpRight className="size-4" />
                    </Link>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/70 p-10 text-center text-sm text-muted-foreground">
              No tasks yet. Workflow rules and record detail pages will create operational follow-ups here.
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
