"use client";

import Link from "next/link";
import { ArrowUpRight, Bot, Clock3, ListTodo, TriangleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { type WorkflowTaskRow, formatDateLabel, taskTone } from "@/lib/workflow";
import { TaskCreateModal, TaskInlineUpdateForm } from "@/components/workflow/task-controls";

type CohortOption = {
  id: string;
  name: string;
  status: string;
};

function isOverdue(task: WorkflowTaskRow) {
  if (!task.due_at) return false;
  return new Date(task.due_at).getTime() < Date.now() && !["Done", "Closed"].includes(task.status);
}

export function TasksWorkspace({
  tasks,
  cohorts,
}: {
  tasks: WorkflowTaskRow[];
  cohorts: CohortOption[];
}) {
  const defaultCohort = cohorts.find((cohort) => cohort.status === "active") ?? cohorts[0];
  const openCount = tasks.filter((task) => task.status === "Open").length;
  const inProgressCount = tasks.filter((task) => task.status === "In Progress").length;
  const overdueCount = tasks.filter(isOverdue).length;

  return (
    <div className="space-y-6">
      <section className="overflow-hidden rounded-[2rem] border border-white/70 bg-slate-950 text-white shadow-glow">
        <div className="grid gap-6 p-6 md:grid-cols-[1.1fr_0.9fr] md:p-8">
          <div>
            <Badge className="mb-5 bg-white/10 text-white">Queue workspace</Badge>
            <h1 className="font-display text-4xl font-semibold tracking-tight md:text-6xl">Operational task queue</h1>
            <p className="mt-5 max-w-2xl text-sm leading-7 text-white/68">
              Follow-up tasks generated by operations work, workflow rules, and manual coordination all live here.
            </p>
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-3xl bg-white p-4 text-slate-950">
              <p className="text-3xl font-semibold">{openCount}</p>
              <p className="text-xs text-slate-500">Open</p>
            </div>
            <div className="rounded-3xl bg-white p-4 text-slate-950">
              <p className="text-3xl font-semibold">{inProgressCount}</p>
              <p className="text-xs text-slate-500">In progress</p>
            </div>
            <div className="rounded-3xl bg-rose-300 p-4 text-slate-950">
              <p className="text-3xl font-semibold">{overdueCount}</p>
              <p className="text-xs font-medium">Overdue</p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">My tasks</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">{tasks.filter((task) => task.assigned_label).length}</p>
              <p className="mt-2 text-xs text-muted-foreground">Tasks already assigned to an owner or team.</p>
            </div>
            <Bot className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Needs review</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">
                {tasks.filter((task) => task.title.toLowerCase().includes("review")).length}
              </p>
              <p className="mt-2 text-xs text-muted-foreground">Review-related follow-ups generated across the system.</p>
            </div>
            <ListTodo className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">At risk</p>
              <p className="mt-2 text-4xl font-semibold tracking-tight">{tasks.filter((task) => task.priority === "High").length}</p>
              <p className="mt-2 text-xs text-muted-foreground">High-priority operational tasks requiring attention.</p>
            </div>
            <TriangleAlert className="size-5 text-muted-foreground" />
          </div>
        </Card>
      </section>

      <Card className="space-y-4">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="font-display text-2xl font-semibold">All tasks</h2>
            <p className="text-sm text-muted-foreground">Update ownership, due dates, or status directly from the queue.</p>
          </div>
          {defaultCohort ? (
            <TaskCreateModal
              title="Create operational task"
              description="Add a standalone task without linking it to an existing record."
              triggerLabel="Add task"
              cohortId={defaultCohort.id}
              cohortName={defaultCohort.name}
              returnTo="/tasks"
            />
          ) : null}
        </div>

        <div className="space-y-3">
          {tasks.length ? (
            tasks.map((task) => (
              <div key={task.id} className="rounded-[1.6rem] border border-slate-200 bg-white p-4">
                <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={taskTone(task.status, task.priority)}>{task.status}</Badge>
                      <Badge>{task.priority}</Badge>
                      {isOverdue(task) ? <Badge tone="red">Overdue</Badge> : null}
                    </div>
                    <h3 className="mt-3 text-lg font-semibold text-slate-950">{task.title}</h3>
                    {task.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{task.description}</p> : null}
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Clock3 className="size-3.5" />
                        {formatDateLabel(task.due_at)}
                      </span>
                      <span>{task.assigned_label || "Unassigned"}</span>
                    </div>
                  </div>

                  <div className="w-full max-w-xl space-y-3">
                    <TaskInlineUpdateForm task={task} returnTo="/tasks" />
                    {task.source_record_type && task.source_record_id ? (
                      <Link
                        href={`/records/${task.source_record_type}/${task.source_record_id}`}
                        className="inline-flex items-center gap-2 text-sm font-medium text-slate-700 transition hover:text-slate-950"
                      >
                        Open linked record
                        <ArrowUpRight className="size-4" />
                      </Link>
                    ) : (
                      <p className="text-sm text-muted-foreground">Standalone operational task</p>
                    )}
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="rounded-[1.5rem] border border-dashed border-slate-200 bg-slate-50/70 p-10 text-center text-sm text-muted-foreground">
              No tasks yet. Create one from the Add task modal or add linked follow-up tasks from a record detail page.
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
