"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowUpRight, Bot, Clock3, ListTodo, TriangleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { CohortSwitcher } from "@/components/cohort-switcher";
import { type WorkflowTaskRow, formatDateLabel, taskTone } from "@/lib/workflow";
import { TaskCreateModal, TaskInlineUpdateForm } from "@/components/workflow/task-controls";

type CohortOption = {
  id: string;
  name: string;
  status: string;
};

function isOverdue(task: WorkflowTaskRow) {
  if (!task.due_at) return false;
  return new Date(task.due_at).getTime() < Date.now() && !["Done", "Closed"].includes(task.status);
}

export function TasksWorkspace({
  tasks,
  cohorts,
  activeCohortId,
  currentUserId,
  assignees,
}: {
  tasks: WorkflowTaskRow[];
  cohorts: CohortOption[];
  activeCohortId: string | null;
  currentUserId: string | null;
  assignees: Array<{ id: string; label: string }>;
}) {
  const defaultCohort = cohorts.find((cohort) => cohort.status === "active") ?? cohorts[0];
  const [view, setView] = useState<"mine" | "due-soon" | "overdue" | "unassigned" | "all">("all");
  const openCount = tasks.filter((task) => task.status === "Open").length;
  const inProgressCount = tasks.filter((task) => task.status === "In Progress").length;
  const overdueCount = tasks.filter(isOverdue).length;
  const dueSoonCount = tasks.filter((task) => {
    if (!task.due_at || ["Done", "Closed"].includes(task.status)) return false;
    const dueAt = new Date(task.due_at).getTime();
    const now = Date.now();
    return dueAt >= now && dueAt <= now + 24 * 60 * 60 * 1000;
  }).length;
  const filteredTasks = tasks.filter((task) => {
    switch (view) {
      case "mine":
        return currentUserId ? task.assigned_to === currentUserId : false;
      case "due-soon":
        if (!task.due_at || ["Done", "Closed"].includes(task.status)) return false;
        {
          const dueAt = new Date(task.due_at).getTime();
          const now = Date.now();
          return dueAt >= now && dueAt <= now + 24 * 60 * 60 * 1000;
        }
      case "overdue":
        return isOverdue(task);
      case "unassigned":
        return !task.assigned_to;
      case "all":
      default:
        return true;
    }
  });

  return (
    <div className="space-y-6">
      <section className="app-panel overflow-hidden p-6 md:p-7">
        <div className="grid gap-6 md:grid-cols-[1.1fr_0.9fr]">
          <div>
            <Badge tone="blue" className="mb-4">Queue workspace</Badge>
            <h1 className="text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">Operational task queue</h1>
            <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
              Follow-up tasks generated by operations work, workflow rules, and manual coordination all live here.
            </p>
            <div className="mt-4">
              <CohortSwitcher
                cohorts={cohorts.map((cohort) => ({ id: cohort.id, name: cohort.name }))}
                activeCohortId={activeCohortId}
                basePath="/tasks"
              />
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="app-panel-subtle p-4">
              <p className="text-3xl font-semibold text-slate-950">{openCount}</p>
              <p className="text-xs text-slate-500">Open</p>
            </div>
            <div className="app-panel-subtle p-4">
              <p className="text-3xl font-semibold text-slate-950">{dueSoonCount}</p>
              <p className="text-xs text-slate-500">Due soon</p>
            </div>
            <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-slate-950">
              <p className="text-3xl font-semibold">{overdueCount}</p>
              <p className="text-xs font-medium text-rose-700">Overdue</p>
            </div>
          </div>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">My tasks</p>
              <p className="mt-2 text-3xl font-semibold tracking-tight">{tasks.filter((task) => currentUserId && task.assigned_to === currentUserId).length}</p>
              <p className="mt-2 text-xs text-muted-foreground">Tasks already assigned to an owner or team.</p>
            </div>
            <Bot className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Needs review</p>
              <p className="mt-2 text-3xl font-semibold tracking-tight">
                {tasks.filter((task) => task.title.toLowerCase().includes("review")).length}
              </p>
              <p className="mt-2 text-xs text-muted-foreground">Review-related follow-ups generated across the system.</p>
            </div>
            <ListTodo className="size-5 text-muted-foreground" />
          </div>
        </Card>
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-sm text-muted-foreground">At risk</p>
              <p className="mt-2 text-3xl font-semibold tracking-tight">{tasks.filter((task) => task.priority === "High").length}</p>
              <p className="mt-2 text-xs text-muted-foreground">High-priority operational tasks requiring attention.</p>
            </div>
            <TriangleAlert className="size-5 text-muted-foreground" />
          </div>
        </Card>
      </section>

      <Card className="space-y-4">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="text-xl font-semibold">All tasks</h2>
            <p className="text-sm text-muted-foreground">Update ownership, due dates, or status directly from the queue.</p>
          </div>
          {defaultCohort ? (
            <TaskCreateModal
              title="Create operational task"
              description="Add a standalone task without linking it to an existing record."
              triggerLabel="Add task"
              cohortId={defaultCohort.id}
              cohortName={defaultCohort.name}
              returnTo="/tasks"
              assignees={assignees}
            />
          ) : null}
        </div>

        <div className="flex flex-wrap gap-2">
          {[
            ["all", "All"],
            ["mine", "My Work"],
            ["due-soon", "Due Soon"],
            ["overdue", "Overdue"],
            ["unassigned", "Unassigned"],
          ].map(([key, label]) => (
            <button
              key={key}
              type="button"
              onClick={() => setView(key as typeof view)}
              className={`inline-flex items-center rounded-xl border px-3 py-2 text-xs font-medium transition ${
                view === key ? "border-slate-950 bg-slate-950 text-white" : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"
              }`}
            >
              {label}
            </button>
          ))}
        </div>

        <div className="space-y-3">
          {filteredTasks.length ? (
            filteredTasks.map((task) => (
              <div key={task.id} className="rounded-2xl border border-slate-200 bg-white p-4">
                <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={taskTone(task.status, task.priority)}>{task.status}</Badge>
                      <Badge>{task.priority}</Badge>
                      {isOverdue(task) ? <Badge tone="red">Overdue</Badge> : null}
                    </div>
                    <h3 className="mt-2.5 text-base font-semibold text-slate-950">{task.title}</h3>
                    {task.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{task.description}</p> : null}
                    <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                      <span className="inline-flex items-center gap-1">
                        <Clock3 className="size-3.5" />
                        {formatDateLabel(task.due_at)}
                      </span>
                      <span>{task.assigned_label || "Unassigned"}</span>
                    </div>
                  </div>

                  <div className="w-full max-w-xl space-y-3">
                    <TaskInlineUpdateForm task={task} returnTo="/tasks" assignees={assignees} />
                    {task.source_record_type && task.source_record_id ? (
                      <Link
                        href={activeCohortId ? `/records/${task.source_record_type}/${task.source_record_id}?cohort=${activeCohortId}` : `/records/${task.source_record_type}/${task.source_record_id}`}
                        className="inline-flex items-center gap-2 text-sm font-medium text-slate-700 transition hover:text-slate-950"
                      >
                        Open linked record
                        <ArrowUpRight className="size-4" />
                      </Link>
                    ) : (
                      <p className="text-sm text-muted-foreground">Standalone operational task</p>
                    )}
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/70 p-10 text-center text-sm text-muted-foreground">
              No tasks match this view yet. Create one from the Add task modal or add linked follow-up tasks from a record detail page.
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
